# Generated by Django 5.2.10 on 2026-01-14 13:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма выплаты')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('KZT', 'Казахстанский тенге')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('recipient_details', models.JSONField(verbose_name='Реквизиты получателя')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'В обработке'), ('completed', 'Выплачено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание/Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='api_app_pay_status_6c6838_idx'), models.Index(fields=['created_at'], name='api_app_pay_created_c7c8aa_idx')],
            },
        ),
    ]
