# Generated by Django 5.2.10 on 2026-01-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payout',
            new_name='api_payouts_status_f5fe30_idx',
            old_name='api_app_pay_status_6c6838_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='api_payouts_created_0dcb1b_idx',
            old_name='api_app_pay_created_c7c8aa_idx',
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма выплаты'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
